[package]
name = "komotool_assets"
version = "0.1.0"
edition = "2021"

[dependencies]
pathdiff = "0.2.3"
bevy = { workspace = true, default-features = false, features = ["bevy_asset", "file_watcher"]}
