[package]
name = "komotool"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }

[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.15.1", default-features = false }
anyhow = "1.0"
serde_json = "1.0"
komorebi_client = "0.1"
log = "0.4"
