[package]
name = "komotool_lua"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true, default-features = false, features = ["bevy_state"]}
bevy_mod_scripting = {workspace = true}
komotool_utils = {path = "../komotool_utils"}
