[package]
name = "komotool_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true, default-features = false }
komorebi-client = {workspace = true}
serde_json = "1.0.138"
indexmap = "2.7.1"
komotool_pipe = { path = "../komotool_pipe"}
