[package]
name = "komotool_ecs"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_ecs = {workspace = true}
bevy_app = {workspace = true}
bevy_reflect = {workspace = true}
komorebi-client = {workspace = true}
serde_json = { version = "1.0.138", features = ["preserve_order"] }
indexmap = "2.7.1"
komotool_pipe = { path = "../komotool_pipe"}
