[package]
name = "komotool_pipe"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true, default-features = false }
anyhow = { workspace = true }
serde_json = { workspace = true }
komorebi-client = { workspace = true }
log = { workspace = true }
